version: '3'
services:
  todo-backend:
    build: .
    container_name: todo-backend
    ports:
      - 8080:8080
    depends_on:
      - mysql
      - prometheus
    environment:
      DB_HOST: mysql
    networks:
      - todo-network

  mysql:
    image: mysql:latest
    container_name: mysql
    environment:
      - MYSQL_ROOT_PASSWORD=mysql-root
    ports:
      - 3306:3306
    restart: unless-stopped
    networks:
      - todo-network

  prometheus:
    image: prom/prometheus
    container_name: prometheus
    volumes:
      - ./config:/prometheus
      - ./data/prometheus:/data
    command:
      - '--config.file=/prometheus.yml'
      - '--storage.tsdb.path=/prometheus-data'
    ports:
      - 9090:9090
    restart: unless-stopped
    networks:
      - todo-network

networks:
  todo-network:
    driver: bridge

volumes:
  prometheus-data: